from typing import Protocol

from app.domain.models import Chunk, Document


class KnowledgeRepository(Protocol):
    def initialize(self) -> None: ...
    def add_document(self, document: Document, chunks: list[Chunk]) -> None: ...
    def list_documents(self) -> list[Document]: ...
    def get_document(self, document_id: str) -> Document | None: ...
    def delete_document(self, document_id: str) -> Document | None: ...
    def search(self, query: str, top_k: int, domain: str | None = None) -> list[Chunk]: ...
